/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.clienteDAO;
import Modelo.Cliente;
import Validar.ConvertirMayusculas;
import Validar.Validar;
import javax.swing.JOptionPane;

/**
 *
 * @author Reaper
 */
public class frmClientes extends javax.swing.JFrame {

    Validar val = new Validar();
    clienteDAO clienteDAO = new clienteDAO();
    Cliente client;
    String cedula;
    public static String cedulaGlobal;
    
    public frmClientes() {
        initComponents();
        this.setLocationRelativeTo(null);
        val.validarNumeros(txtCedula);
        val.validarLetras(txtNombre);
        val.validarLetras(txtApellido);
        val.validarNumeros(txtTelefono);
        val.validarNumeros(txtPeso);
        val.validarNumeros(txtTalla);
        val.validarNumeros(txtSistole);
        val.validarNumeros(txtDiastole);
        val.limitarCaracteres(txtCedula, 10);
        txtNombre.setDocument(new ConvertirMayusculas());
        txtApellido.setDocument(new ConvertirMayusculas());
        txtDireccion.setDocument(new ConvertirMayusculas());
        val.limitarCaracteres(txtDlgCedula, 10);
        val.validarNumeros(txtDlgCedula);
        btnInsertar.setEnabled(false);
        verBotones(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgModificar = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        txtDlgCedula = new javax.swing.JTextField();
        btnDlgAceptar = new javax.swing.JButton();
        btnDlgCancelar = new javax.swing.JButton();
        dlgEliminar = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        txtDlgCedulaEliminar = new javax.swing.JTextField();
        btnDlgEliminar = new javax.swing.JButton();
        btnDlgCancelar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        txtCedula = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        txtTalla = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        cmbGrupoSanguineo = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        cmbFactorRH = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtSistole = new javax.swing.JTextField();
        txtDiastole = new javax.swing.JTextField();
        cmbSexo = new javax.swing.JComboBox<>();
        btnHome = new javax.swing.JButton();
        btnCancelarModificar = new javax.swing.JButton();
        btnAceptarModificar = new javax.swing.JButton();

        dlgModificar.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        dlgModificar.setMinimumSize(new java.awt.Dimension(400, 180));

        jLabel10.setText("Ingrese el número de cédula");

        txtDlgCedula.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtDlgCedulaCaretUpdate(evt);
            }
        });

        btnDlgAceptar.setText("Aceptar");
        btnDlgAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDlgAceptarActionPerformed(evt);
            }
        });

        btnDlgCancelar.setText("Cancelar");
        btnDlgCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDlgCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgModificarLayout = new javax.swing.GroupLayout(dlgModificar.getContentPane());
        dlgModificar.getContentPane().setLayout(dlgModificarLayout);
        dlgModificarLayout.setHorizontalGroup(
            dlgModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgModificarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(dlgModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(dlgModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(dlgModificarLayout.createSequentialGroup()
                            .addComponent(btnDlgAceptar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDlgCancelar))
                        .addComponent(txtDlgCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        dlgModificarLayout.setVerticalGroup(
            dlgModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgModificarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDlgCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dlgModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDlgAceptar)
                    .addComponent(btnDlgCancelar))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        dlgEliminar.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        dlgEliminar.setMinimumSize(new java.awt.Dimension(400, 180));

        jLabel11.setText("Ingrese el número de cédula");

        txtDlgCedulaEliminar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtDlgCedulaEliminarCaretUpdate(evt);
            }
        });

        btnDlgEliminar.setText("Eliminar");
        btnDlgEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDlgEliminarActionPerformed(evt);
            }
        });

        btnDlgCancelar1.setText("Cancelar");
        btnDlgCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDlgCancelar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgEliminarLayout = new javax.swing.GroupLayout(dlgEliminar.getContentPane());
        dlgEliminar.getContentPane().setLayout(dlgEliminarLayout);
        dlgEliminarLayout.setHorizontalGroup(
            dlgEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgEliminarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(dlgEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(dlgEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(dlgEliminarLayout.createSequentialGroup()
                            .addComponent(btnDlgEliminar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDlgCancelar1))
                        .addComponent(txtDlgCedulaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        dlgEliminarLayout.setVerticalGroup(
            dlgEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgEliminarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDlgCedulaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dlgEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDlgEliminar)
                    .addComponent(btnDlgCancelar1))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DATOS DEL CLIENTE");

        jLabel2.setText("Cedula");

        jLabel3.setText("Nombre");

        jLabel4.setText("Apellido");

        jLabel5.setText("Direccion");

        jLabel6.setText("Telefono");

        jLabel7.setText("Sexo");

        jLabel8.setText("Peso");

        jLabel9.setText("Talla");

        jLabel12.setText("Observaciones");

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane1.setViewportView(txtObservaciones);

        txtCedula.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtCedulaCaretUpdate(evt);
            }
        });

        txtApellido.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtApellidoCaretUpdate(evt);
            }
        });

        txtNombre.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtNombreCaretUpdate(evt);
            }
        });

        txtDireccion.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtDireccionCaretUpdate(evt);
            }
        });

        txtTelefono.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTelefonoCaretUpdate(evt);
            }
        });

        txtPeso.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPesoCaretUpdate(evt);
            }
        });

        txtTalla.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTallaCaretUpdate(evt);
            }
        });

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Sangre"));

        jLabel14.setText("Grupo sanguineo");

        cmbGrupoSanguineo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "AB", "O" }));

        jLabel15.setText("Factor RH");

        cmbFactorRH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbGrupoSanguineo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbFactorRH, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cmbGrupoSanguineo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cmbFactorRH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Frecuencia cardiaca"));

        jLabel16.setText("Sistole");

        jLabel17.setText("Diastole");

        txtSistole.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSistoleCaretUpdate(evt);
            }
        });

        txtDiastole.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtDiastoleCaretUpdate(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDiastole)
                    .addComponent(txtSistole))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtSistole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtDiastole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/home.png"))); // NOI18N
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnCancelarModificar.setText("Cancelar");
        btnCancelarModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarModificarActionPerformed(evt);
            }
        });

        btnAceptarModificar.setText("Aceptar");
        btnAceptarModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(393, 393, 393))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTalla, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                            .addComponent(cmbSexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInsertar)
                        .addGap(141, 141, 141)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAceptarModificar)
                        .addGap(55, 55, 55)
                        .addComponent(btnCancelarModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtTalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCancelarModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEliminar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnModificar)
                        .addComponent(btnInsertar))
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptarModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verficarCampos()
    {
        String cedula, nombre, apellido, direccion, telefono, sistole, diastole, peso, talla;
        cedula=txtCedula.getText().trim();
        nombre= txtNombre.getText().trim();
        apellido = txtApellido.getText().trim();
        direccion = txtDireccion.getText().trim();
        telefono = txtTelefono.getText().trim();
        sistole = txtSistole.getText().trim();
        diastole = txtDiastole.getText().trim();
        peso = (txtPeso.getText().trim());
        talla = (txtTalla.getText().trim());
        
        if (cedula.isEmpty() || nombre.isEmpty() || apellido.isEmpty() || direccion.isEmpty() || telefono.isEmpty()
                || sistole.isEmpty() || diastole.isEmpty() || peso.isEmpty() || talla.isEmpty())
        {
            btnInsertar.setEnabled(false);
        }
        else{
            btnInsertar.setEnabled(true);
        }
    }
    
    private void limpiarCampos()
    {
        txtCedula.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtPeso.setText("");
        txtTalla.setText("");
        txtSistole.setText("");
        txtDiastole.setText("");
        txtObservaciones.setText("");
    }
    
    private void verBotones(boolean ver)
    {
        btnAceptarModificar.setVisible(!ver);
        btnCancelarModificar.setVisible(!ver);
        btnInsertar.setVisible(ver);
        btnModificar.setVisible(ver);
        btnEliminar.setVisible(ver);
    }
    
    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        frmPresentacion pres = new frmPresentacion();
        pres.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        if (val.validacionCedula(txtCedula.getText().trim()))
        {
            String cedula, nombre, apellido, direccion, telefono,sangre, presion, observaciones, sexo;
            float peso, talla;
            
            cedula=txtCedula.getText().trim();
            cedulaGlobal=cedula;
            nombre= txtNombre.getText().trim();
            apellido = txtApellido.getText().trim();
            direccion = txtDireccion.getText().trim();
            telefono = txtTelefono.getText().trim();
            sexo = cmbSexo.getSelectedItem().toString();
            observaciones = txtObservaciones.getText().trim();
            
            peso = Float.parseFloat(txtPeso.getText().trim());
            talla = Float.parseFloat(txtTalla.getText().trim());
            
            sangre = cmbGrupoSanguineo.getSelectedItem().toString() + "_" + cmbFactorRH.getSelectedItem().toString();
            presion = txtSistole.getText().trim()+"/"+txtDiastole.getText().trim();
            

            client = new Cliente(cedula, nombre, apellido, direccion, telefono, sangre, presion, observaciones, sexo, peso, talla);
            
            if (clienteDAO.registrarCliente(client))
            {
                this.dispose();
                frmSerologia ser = new frmSerologia();
                ser.setVisible(true);
            }
            limpiarCampos();
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Cedula incorrecta!!");
            txtCedula.setText("");
        }
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        dlgModificar.setLocationRelativeTo(this);
        dlgModificar.setVisible(true);
        btnDlgAceptar.setEnabled(false);
        this.setEnabled(false);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtDlgCedulaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtDlgCedulaCaretUpdate
        String cedula=txtDlgCedula.getText().trim();
        if (cedula.length()!=10)
        btnDlgAceptar.setEnabled(false);
        else
        {
            btnDlgAceptar.setEnabled(true);
        }
    }//GEN-LAST:event_txtDlgCedulaCaretUpdate

    private void btnDlgAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDlgAceptarActionPerformed
        String[] datosCliente = new String[11];
        datosCliente = clienteDAO.getDatosCliente(txtDlgCedula.getText().trim());
        this.setEnabled(true);
        dlgModificar.dispose();
        txtCedula.setText(datosCliente[0]);
        txtCedula.setEditable(false);
        txtNombre.setText(datosCliente[1]);
        txtApellido.setText(datosCliente[2]);
        txtDireccion.setText(datosCliente[3]);
        txtTelefono.setText(datosCliente[4]);
        
        String sexo = datosCliente[5];
        System.out.println(sexo);
        if (sexo.equals("Masculino"))
        {
            cmbSexo.setSelectedIndex(0);
        }
        else
        {
            cmbSexo.setSelectedIndex(1);
        }
        
        txtPeso.setText(datosCliente[6]);   
        txtTalla.setText(datosCliente[7]);
        txtObservaciones.setText(datosCliente[10]);
        
        //sangre
        String[] splitSangre = datosCliente[8].split("_");
        switch (splitSangre[0])
        {
            case "A":   
            {
                cmbGrupoSanguineo.setSelectedIndex(0);
                break;
            }
                
            case "B":   
            {
                cmbGrupoSanguineo.setSelectedIndex(1);
                break;
            }
            
            case "C":   
            {
                cmbGrupoSanguineo.setSelectedIndex(2);
                break;
            }
            
            case "D":   
            {
                cmbGrupoSanguineo.setSelectedIndex(3);
                break;
            }   
        }
        
        switch(splitSangre[1])
        {
            case "+":
                cmbFactorRH.setSelectedIndex(0);
                break;
            case "-":
                cmbFactorRH.setSelectedIndex(1);
        }
        
        //presion
        String[] splitPresion = datosCliente[9].split("/");
        txtSistole.setText(splitPresion[0]);
        txtDiastole.setText(splitPresion[1]);
        verBotones(false);
    }//GEN-LAST:event_btnDlgAceptarActionPerformed

    private void btnDlgCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDlgCancelarActionPerformed
        this.setEnabled(true);
        dlgModificar.dispose();
    }//GEN-LAST:event_btnDlgCancelarActionPerformed

    private void txtDlgCedulaEliminarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtDlgCedulaEliminarCaretUpdate
        String cedula=txtDlgCedulaEliminar.getText().trim();
        if (cedula.length()!=10)
        btnDlgEliminar.setEnabled(false);
        else
        {
            btnDlgEliminar.setEnabled(true);
        }
    }//GEN-LAST:event_txtDlgCedulaEliminarCaretUpdate

    private void btnDlgEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDlgEliminarActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Desea eliminar el registro?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            clienteDAO.eliminarCliente(txtDlgCedulaEliminar.getText().trim());
        }
        dlgEliminar.dispose();
        this.setEnabled(true);
        this.setVisible(true);
    }//GEN-LAST:event_btnDlgEliminarActionPerformed

    private void btnDlgCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDlgCancelar1ActionPerformed
        this.setEnabled(true);
        dlgEliminar.dispose();
        verBotones(true);
        limpiarCampos();
        this.setVisible(true);
    }//GEN-LAST:event_btnDlgCancelar1ActionPerformed

    private void btnCancelarModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarModificarActionPerformed
        verBotones(true);
        limpiarCampos();
    }//GEN-LAST:event_btnCancelarModificarActionPerformed

    private void btnAceptarModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarModificarActionPerformed
        String cedula, nombre, apellido, direccion, telefono,sangre, presion, observaciones, sexo;
        float peso, talla;

        cedula=txtCedula.getText().trim();
        nombre= txtNombre.getText().trim();
        apellido = txtApellido.getText().trim();
        direccion = txtDireccion.getText().trim();
        telefono = txtTelefono.getText().trim();
        sexo = cmbSexo.getSelectedItem().toString();
        observaciones = txtObservaciones.getText().trim();

        peso = Float.parseFloat(txtPeso.getText().trim());
        talla = Float.parseFloat(txtTalla.getText().trim());

        sangre = cmbGrupoSanguineo.getSelectedItem().toString() + "_" + cmbFactorRH.getSelectedItem().toString();
        presion = txtSistole.getText().trim()+"/"+txtDiastole.getText().trim();


        client = new Cliente(cedula, nombre, apellido, direccion, telefono, sangre, presion, observaciones, sexo, peso, talla);
        
        clienteDAO.modificarCliente(client);
        limpiarCampos();
        verBotones(true);
        txtCedula.setEditable(false);
    }//GEN-LAST:event_btnAceptarModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        dlgEliminar.setLocationRelativeTo(this);
        dlgEliminar.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtCedulaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtCedulaCaretUpdate
        verficarCampos();
    }//GEN-LAST:event_txtCedulaCaretUpdate

    private void txtNombreCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtNombreCaretUpdate
        verficarCampos();
    }//GEN-LAST:event_txtNombreCaretUpdate

    private void txtApellidoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtApellidoCaretUpdate
        verficarCampos();
    }//GEN-LAST:event_txtApellidoCaretUpdate

    private void txtDireccionCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtDireccionCaretUpdate
        verficarCampos();
    }//GEN-LAST:event_txtDireccionCaretUpdate

    private void txtTelefonoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTelefonoCaretUpdate
        verficarCampos();
    }//GEN-LAST:event_txtTelefonoCaretUpdate

    private void txtPesoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPesoCaretUpdate
        verficarCampos();
    }//GEN-LAST:event_txtPesoCaretUpdate

    private void txtTallaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTallaCaretUpdate
        verficarCampos();
    }//GEN-LAST:event_txtTallaCaretUpdate

    private void txtSistoleCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSistoleCaretUpdate
        verficarCampos();
    }//GEN-LAST:event_txtSistoleCaretUpdate

    private void txtDiastoleCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtDiastoleCaretUpdate
        verficarCampos();
    }//GEN-LAST:event_txtDiastoleCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarModificar;
    private javax.swing.JButton btnCancelarModificar;
    private javax.swing.JButton btnDlgAceptar;
    private javax.swing.JButton btnDlgCancelar;
    private javax.swing.JButton btnDlgCancelar1;
    private javax.swing.JButton btnDlgEliminar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbFactorRH;
    private javax.swing.JComboBox<String> cmbGrupoSanguineo;
    private javax.swing.JComboBox<String> cmbSexo;
    private javax.swing.JDialog dlgEliminar;
    private javax.swing.JDialog dlgModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDiastole;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDlgCedula;
    private javax.swing.JTextField txtDlgCedulaEliminar;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtObservaciones;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtSistole;
    private javax.swing.JTextField txtTalla;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
