/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Modelo.Conexion;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Reaper
 */
public class frmPresentacion extends javax.swing.JFrame {

    /**
     * Creates new form frmPresentacion
     */
    public frmPresentacion() {
        initComponents();
        this.setLocationRelativeTo(null);
        mnuCrearUsuario.setEnabled(frmIngreso.admin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        mnuReporteExtraccion = new javax.swing.JMenuItem();
        mnuReporteTransfucion = new javax.swing.JMenuItem();
        mnuReporteUsuarios = new javax.swing.JMenuItem();
        mnuReporteClientes = new javax.swing.JMenuItem();
        mnuSerologia = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuCrearUsuario = new javax.swing.JMenuItem();
        mnuCrearCliente = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mnuBuscarSangre = new javax.swing.JMenuItem();
        mnuDonacionTransfucion = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu2.setText("Archivo");

        mnuReporteExtraccion.setText("Reporte de donacion");
        mnuReporteExtraccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReporteExtraccionActionPerformed(evt);
            }
        });
        jMenu2.add(mnuReporteExtraccion);

        mnuReporteTransfucion.setText("Reporte de transfucion");
        mnuReporteTransfucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReporteTransfucionActionPerformed(evt);
            }
        });
        jMenu2.add(mnuReporteTransfucion);

        mnuReporteUsuarios.setText("Reporte de usuarios");
        mnuReporteUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReporteUsuariosActionPerformed(evt);
            }
        });
        jMenu2.add(mnuReporteUsuarios);

        mnuReporteClientes.setText("Reporte de clientes");
        mnuReporteClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReporteClientesActionPerformed(evt);
            }
        });
        jMenu2.add(mnuReporteClientes);

        mnuSerologia.setText("Reporte de serología");
        mnuSerologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSerologiaActionPerformed(evt);
            }
        });
        jMenu2.add(mnuSerologia);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Personal");

        mnuCrearUsuario.setText("Usuario");
        mnuCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCrearUsuarioActionPerformed(evt);
            }
        });
        jMenu3.add(mnuCrearUsuario);

        mnuCrearCliente.setText("Cliente");
        mnuCrearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCrearClienteActionPerformed(evt);
            }
        });
        jMenu3.add(mnuCrearCliente);

        jMenuBar1.add(jMenu3);

        jMenu6.setText("Pintas de Sangre");

        mnuBuscarSangre.setText("Busqueda");
        jMenu6.add(mnuBuscarSangre);

        jMenuBar1.add(jMenu6);

        mnuDonacionTransfucion.setText("Donacion/Transfucion");
        mnuDonacionTransfucion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnuDonacionTransfucionMousePressed(evt);
            }
        });
        jMenuBar1.add(mnuDonacionTransfucion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1029, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuDonacionTransfucionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuDonacionTransfucionMousePressed
        frmDonacionTransfucion donTra = new frmDonacionTransfucion();
        donTra.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuDonacionTransfucionMousePressed

    private void mnuReporteTransfucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReporteTransfucionActionPerformed
        try {
            Conexion con = new Conexion();
            Connection conn = con.getConexion();
            
            JasperReport reporte = null;
            String path = "src\\Report\\Transfucion.jasper";
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
            
            JasperPrint jprint = JasperFillManager.fillReport(path, null, conn);
            
            JasperViewer view = new JasperViewer(jprint, false);
            
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            
            view.setVisible(true);
            
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "Error al generar reporte!!");
        }
    }//GEN-LAST:event_mnuReporteTransfucionActionPerformed

    private void mnuCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCrearUsuarioActionPerformed
        frmUsuarios userWin = new frmUsuarios();
        userWin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuCrearUsuarioActionPerformed

    private void mnuReporteUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReporteUsuariosActionPerformed
        try {
            Conexion con = new Conexion();
            Connection conn = con.getConexion();
            
            JasperReport reporte = null;
            String path = "src\\Report\\Usuarios.jasper";
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
            
            JasperPrint jprint = JasperFillManager.fillReport(path, null, conn);
            
            JasperViewer view = new JasperViewer(jprint, false);
            
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            
            view.setVisible(true);
            
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "Error al generar reporte!!");
        }
    }//GEN-LAST:event_mnuReporteUsuariosActionPerformed

    private void mnuCrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCrearClienteActionPerformed
        frmClientes cli = new frmClientes();
        cli.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuCrearClienteActionPerformed

    private void mnuReporteClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReporteClientesActionPerformed
        try {
            Conexion con = new Conexion();
            Connection conn = con.getConexion();
            
            JasperReport reporte = null;
            String path = "src\\Report\\Clientes.jasper";
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
            
            JasperPrint jprint = JasperFillManager.fillReport(path, null, conn);
            
            JasperViewer view = new JasperViewer(jprint, false);
            
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            
            view.setVisible(true);
            
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "Error al generar reporte!!");
        }
    }//GEN-LAST:event_mnuReporteClientesActionPerformed

    private void mnuSerologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSerologiaActionPerformed
        try {
            Map parametro = new HashMap();
            Conexion con = new Conexion();
            Connection conn = con.getConexion();
            String path = "src\\Report\\Serologia.jasper";
            JasperReport reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
            String cedula = JOptionPane.showInputDialog(null,"Ingrese la cédula del cliente");
            parametro.put("ced", cedula);
            
            JasperPrint jprint = JasperFillManager.fillReport(path, parametro, conn);
            
            JasperViewer view = new JasperViewer(jprint, false);
            
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            
            view.setVisible(true);
            
        } catch (JRException ex) {
            Logger.getLogger(frmPresentacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuSerologiaActionPerformed

    private void mnuReporteExtraccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReporteExtraccionActionPerformed
        try {
            Conexion con = new Conexion();
            Connection conn = con.getConexion();
            
            JasperReport reporte = null;
            String path = "src\\Report\\Donacion.jasper";
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
            
            JasperPrint jprint = JasperFillManager.fillReport(path, null, conn);
            
            JasperViewer view = new JasperViewer(jprint, false);
            
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            
            view.setVisible(true);
            
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "Error al generar reporte!!");
        }
    }//GEN-LAST:event_mnuReporteExtraccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPresentacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuBuscarSangre;
    private javax.swing.JMenuItem mnuCrearCliente;
    private javax.swing.JMenuItem mnuCrearUsuario;
    private javax.swing.JMenu mnuDonacionTransfucion;
    private javax.swing.JMenuItem mnuReporteClientes;
    private javax.swing.JMenuItem mnuReporteExtraccion;
    private javax.swing.JMenuItem mnuReporteTransfucion;
    private javax.swing.JMenuItem mnuReporteUsuarios;
    private javax.swing.JMenuItem mnuSerologia;
    // End of variables declaration//GEN-END:variables
}
