/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.usuarioDAO;
import Modelo.Usuario;
import Validar.ConvertirMayusculas;
import Validar.Validar;
import javax.swing.JOptionPane;

/**
 *
 * @author Reaper
 */
public class frmUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form frmClientes
     */
    Validar val = new Validar();
    usuarioDAO userDAO = new usuarioDAO();
    Usuario user;
    
    public frmUsuarios() {
        initComponents();
        this.setLocationRelativeTo(null);
        val.limitarCaracteres(txtCodigoUsuario, 10);
        val.validarNumeros(txtCodigoUsuario);
        val.validarNumeros(txtTelefonoUsuario);
        val.validarLetras(txtNombreUsuario);
        val.validarLetras(txtApellidoUsuario);
        val.validarNumeros(txtDlgCedulaEliminar);
        txtNombreUsuario.setDocument(new ConvertirMayusculas());
        txtApellidoUsuario.setDocument(new ConvertirMayusculas());
        val.validarNumeros(txtDlgCedula);
        val.limitarCaracteres(txtDlgCedula, 10);
        val.limitarCaracteres(txtDlgCedulaEliminar, 10);
        btnInsertarUsuario.setEnabled(false);
        btnDlgEliminar.setEnabled(false);
        verBotones(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgModificar = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        txtDlgCedula = new javax.swing.JTextField();
        btnDlgAceptar = new javax.swing.JButton();
        btnDlgCancelar = new javax.swing.JButton();
        dlgEliminar = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        txtDlgCedulaEliminar = new javax.swing.JTextField();
        btnDlgEliminar = new javax.swing.JButton();
        btnDlgCancelar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigoUsuario = new javax.swing.JTextField();
        txtNombreUsuario = new javax.swing.JTextField();
        txtApellidoUsuario = new javax.swing.JTextField();
        txtTelefonoUsuario = new javax.swing.JTextField();
        btnInsertarUsuario = new javax.swing.JButton();
        btnModificarUsuario = new javax.swing.JButton();
        btnEliminarUsuario = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        rdAdministradorUsuario = new javax.swing.JRadioButton();
        cmbSexoUsuario = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtPassUsuario = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        txtRepPassUsuario = new javax.swing.JPasswordField();
        btnHome = new javax.swing.JButton();
        btnAceptarModificar = new javax.swing.JButton();
        btnCancelarModificar = new javax.swing.JButton();

        dlgModificar.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        dlgModificar.setMinimumSize(new java.awt.Dimension(400, 180));
        dlgModificar.setPreferredSize(new java.awt.Dimension(400, 180));

        jLabel7.setText("Ingrese el número de cédula");

        txtDlgCedula.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtDlgCedulaCaretUpdate(evt);
            }
        });

        btnDlgAceptar.setText("Aceptar");
        btnDlgAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDlgAceptarActionPerformed(evt);
            }
        });

        btnDlgCancelar.setText("Cancelar");
        btnDlgCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDlgCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgModificarLayout = new javax.swing.GroupLayout(dlgModificar.getContentPane());
        dlgModificar.getContentPane().setLayout(dlgModificarLayout);
        dlgModificarLayout.setHorizontalGroup(
            dlgModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgModificarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(dlgModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(dlgModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(dlgModificarLayout.createSequentialGroup()
                            .addComponent(btnDlgAceptar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDlgCancelar))
                        .addComponent(txtDlgCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        dlgModificarLayout.setVerticalGroup(
            dlgModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgModificarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDlgCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dlgModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDlgAceptar)
                    .addComponent(btnDlgCancelar))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        dlgEliminar.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        dlgEliminar.setMinimumSize(new java.awt.Dimension(400, 180));
        dlgEliminar.setPreferredSize(new java.awt.Dimension(400, 180));

        jLabel10.setText("Ingrese el número de cédula");

        txtDlgCedulaEliminar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtDlgCedulaEliminarCaretUpdate(evt);
            }
        });

        btnDlgEliminar.setText("Eliminar");
        btnDlgEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDlgEliminarActionPerformed(evt);
            }
        });

        btnDlgCancelar1.setText("Cancelar");
        btnDlgCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDlgCancelar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgEliminarLayout = new javax.swing.GroupLayout(dlgEliminar.getContentPane());
        dlgEliminar.getContentPane().setLayout(dlgEliminarLayout);
        dlgEliminarLayout.setHorizontalGroup(
            dlgEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgEliminarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(dlgEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(dlgEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(dlgEliminarLayout.createSequentialGroup()
                            .addComponent(btnDlgEliminar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDlgCancelar1))
                        .addComponent(txtDlgCedulaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        dlgEliminarLayout.setVerticalGroup(
            dlgEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgEliminarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDlgCedulaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dlgEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDlgEliminar)
                    .addComponent(btnDlgCancelar1))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel3.setText("Apellido");

        jLabel4.setText("Cedula");

        jLabel5.setText("Telefono");

        jLabel6.setText("Sexo");

        txtCodigoUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCodigoUsuario.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtCodigoUsuarioCaretUpdate(evt);
            }
        });

        txtNombreUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombreUsuario.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtNombreUsuarioCaretUpdate(evt);
            }
        });

        txtApellidoUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtApellidoUsuario.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtApellidoUsuarioCaretUpdate(evt);
            }
        });

        txtTelefonoUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTelefonoUsuario.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTelefonoUsuarioCaretUpdate(evt);
            }
        });

        btnInsertarUsuario.setText("Insertar");
        btnInsertarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarUsuarioActionPerformed(evt);
            }
        });

        btnModificarUsuario.setText("Modificar");
        btnModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarUsuarioActionPerformed(evt);
            }
        });

        btnEliminarUsuario.setText("Eliminar");
        btnEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUsuarioActionPerformed(evt);
            }
        });

        jLabel8.setText("DATOS DE USUARIO");

        rdAdministradorUsuario.setText("Administrador");

        cmbSexoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        jLabel2.setText("Contraseña");

        txtPassUsuario.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPassUsuarioCaretUpdate(evt);
            }
        });

        jLabel9.setText("Repetir contraseña");

        txtRepPassUsuario.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtRepPassUsuarioCaretUpdate(evt);
            }
        });

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/home.png"))); // NOI18N
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnAceptarModificar.setText("Aceptar");
        btnAceptarModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarModificarActionPerformed(evt);
            }
        });

        btnCancelarModificar.setText("Cancelar");
        btnCancelarModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel8))
                    .addComponent(rdAdministradorUsuario)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(50, 50, 50)
                        .addComponent(txtCodigoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(44, 44, 44)
                        .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(44, 44, 44)
                        .addComponent(txtApellidoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(40, 40, 40)
                        .addComponent(txtTelefonoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(60, 60, 60)
                        .addComponent(cmbSexoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(23, 23, 23)
                        .addComponent(txtPassUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(txtRepPassUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInsertarUsuario)
                            .addComponent(btnAceptarModificar))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(btnEliminarUsuario))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(btnCancelarModificar))
                            .addComponent(btnModificarUsuario))
                        .addGap(24, 24, 24)
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel8)
                .addGap(6, 6, 6)
                .addComponent(rdAdministradorUsuario)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel4))
                    .addComponent(txtCodigoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1))
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3))
                    .addComponent(txtApellidoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5))
                    .addComponent(txtTelefonoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel6))
                    .addComponent(cmbSexoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(txtPassUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(8, 8, 8)
                .addComponent(txtRepPassUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInsertarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptarModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHome))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verBotones(boolean ver)
    {
        btnAceptarModificar.setVisible(!ver);
        btnCancelarModificar.setVisible(!ver);
        btnInsertarUsuario.setVisible(ver);
        btnModificarUsuario.setVisible(ver);
        btnEliminarUsuario.setVisible(ver);
    }
    
    private void limpiarCampos()
    {
        txtCodigoUsuario.setText("");
        txtNombreUsuario.setText("");
        txtApellidoUsuario.setText("");
        txtTelefonoUsuario.setText("");
        txtPassUsuario.setText("");
        txtRepPassUsuario.setText("");
        rdAdministradorUsuario.setSelected(false);
        cmbSexoUsuario.setSelectedIndex(0);
    }
    
    private void confirmarPass()
    {
        String pass, repPass;
        pass = txtPassUsuario.getText().trim();
        repPass = txtRepPassUsuario.getText().trim();
        
        if(pass.equals(repPass))
        {
            btnInsertarUsuario.setEnabled(true);
            btnAceptarModificar.setEnabled(true);
        }
            
        else
        {
            btnInsertarUsuario.setEnabled(false);
            btnAceptarModificar.setEnabled(false);
        }
    }
    
    private void camposVacios()
    {
        String cedula,nombre, apellido, telefono, pass, repPass;
        pass = txtPassUsuario.getText().trim();
        repPass = txtRepPassUsuario.getText().trim();
        cedula = txtCodigoUsuario.getText().trim();
        nombre = txtNombreUsuario.getText().trim();
        apellido = txtApellidoUsuario.getText().trim();
        telefono = txtTelefonoUsuario.getText().trim();
        
        if (pass.isEmpty() || repPass.isEmpty() || cedula.isEmpty() || nombre.isEmpty() || apellido.isEmpty() || telefono.isEmpty())
        {
            btnInsertarUsuario.setEnabled(true);
            btnAceptarModificar.setEnabled(true);
        }
            
        else
        {
            btnInsertarUsuario.setEnabled(false);
            btnAceptarModificar.setEnabled(false);
        }
    }
    
    private void txtPassUsuarioCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPassUsuarioCaretUpdate
        confirmarPass();
    }//GEN-LAST:event_txtPassUsuarioCaretUpdate

    private void txtRepPassUsuarioCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtRepPassUsuarioCaretUpdate
        confirmarPass();
    }//GEN-LAST:event_txtRepPassUsuarioCaretUpdate

    private void btnInsertarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarUsuarioActionPerformed
        String codigo = txtCodigoUsuario.getText().trim();
        String nombre = txtNombreUsuario.getText().trim();
        String apellido = txtApellidoUsuario.getText().trim();
        String pass = txtPassUsuario.getText().trim();
        String telefono = txtTelefonoUsuario.getText().trim();
        String sexo = cmbSexoUsuario.getSelectedItem().toString();
        boolean admin = rdAdministradorUsuario.isSelected();           
        
        if(val.validacionCedula(codigo))
        {
            user = new Usuario(codigo, nombre, apellido, pass, telefono, sexo, admin);
            userDAO.registrarUsuario(user);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Cedula invalida!!");
            txtCodigoUsuario.setText("");
        }
        limpiarCampos();
    }//GEN-LAST:event_btnInsertarUsuarioActionPerformed

    private void txtCodigoUsuarioCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtCodigoUsuarioCaretUpdate
        camposVacios();
    }//GEN-LAST:event_txtCodigoUsuarioCaretUpdate

    private void txtNombreUsuarioCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtNombreUsuarioCaretUpdate
        camposVacios();
    }//GEN-LAST:event_txtNombreUsuarioCaretUpdate

    private void txtApellidoUsuarioCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtApellidoUsuarioCaretUpdate
        camposVacios();
    }//GEN-LAST:event_txtApellidoUsuarioCaretUpdate

    private void txtTelefonoUsuarioCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTelefonoUsuarioCaretUpdate
        camposVacios();
    }//GEN-LAST:event_txtTelefonoUsuarioCaretUpdate

    private void btnEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioActionPerformed
        this.setEnabled(false);
        dlgEliminar.setLocationRelativeTo(this);
        dlgEliminar.setVisible(true);
    }//GEN-LAST:event_btnEliminarUsuarioActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        frmPresentacion pres = new frmPresentacion();
        pres.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnDlgCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDlgCancelarActionPerformed
        this.setEnabled(true);
        dlgModificar.dispose();
    }//GEN-LAST:event_btnDlgCancelarActionPerformed

    private void btnModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarUsuarioActionPerformed
        dlgModificar.setLocationRelativeTo(this);
        dlgModificar.setVisible(true);
        btnDlgAceptar.setEnabled(false);
        this.setEnabled(false);
    }//GEN-LAST:event_btnModificarUsuarioActionPerformed

    private void txtDlgCedulaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtDlgCedulaCaretUpdate
        String cedula=txtDlgCedula.getText().trim();
        if (cedula.length()!=10)
            btnDlgAceptar.setEnabled(false);
        else
        {
            btnDlgAceptar.setEnabled(true);
        }
    }//GEN-LAST:event_txtDlgCedulaCaretUpdate

    private void btnDlgAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDlgAceptarActionPerformed
        String[] datosUsuario = new String[7];
        datosUsuario = userDAO.getDatosUsuario(txtDlgCedula.getText().trim());
        this.setEnabled(true);
        dlgModificar.dispose();
        txtCodigoUsuario.setText(datosUsuario[0]);
        txtCodigoUsuario.setEditable(false);
        txtNombreUsuario.setText(datosUsuario[1]);
        txtApellidoUsuario.setText(datosUsuario[2]);
        txtTelefonoUsuario.setText(datosUsuario[3]);
        txtPassUsuario.setText(datosUsuario[5]);
        
        if(datosUsuario[6].equals("1"))
            rdAdministradorUsuario.setSelected(true);
        else
            rdAdministradorUsuario.setSelected(false);
        
        if(datosUsuario[4].equals("Masculino"))
            cmbSexoUsuario.setSelectedIndex(0);
        else
            cmbSexoUsuario.setSelectedIndex(1);
        
        verBotones(false);
    }//GEN-LAST:event_btnDlgAceptarActionPerformed

    private void btnCancelarModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarModificarActionPerformed
        verBotones(true);
        limpiarCampos();
    }//GEN-LAST:event_btnCancelarModificarActionPerformed

    private void btnAceptarModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarModificarActionPerformed
        String codigo = txtCodigoUsuario.getText().trim();
        String nombre = txtNombreUsuario.getText().trim();
        String apellido = txtApellidoUsuario.getText().trim();
        String pass = txtPassUsuario.getText().trim();
        String telefono = txtTelefonoUsuario.getText().trim();
        String sexo = cmbSexoUsuario.getSelectedItem().toString();
        boolean admin = rdAdministradorUsuario.isSelected();
                  
        
        user = new Usuario(codigo, nombre, apellido, pass, telefono, sexo, admin);
        userDAO.modificarUsuario(user);
        limpiarCampos();
        txtCodigoUsuario.setEditable(true);
    }//GEN-LAST:event_btnAceptarModificarActionPerformed

    private void txtDlgCedulaEliminarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtDlgCedulaEliminarCaretUpdate
        String cedula=txtDlgCedulaEliminar.getText().trim();
        if (cedula.length()!=10)
            btnDlgEliminar.setEnabled(false);
        else
        {
            btnDlgEliminar.setEnabled(true);
        }
    }//GEN-LAST:event_txtDlgCedulaEliminarCaretUpdate

    private void btnDlgEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDlgEliminarActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Desea eliminar el registro?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
          userDAO.eliminarUsuario(txtDlgCedulaEliminar.getText().trim());
        }
        dlgEliminar.dispose();
        this.setEnabled(true);
        this.setVisible(true);
    }//GEN-LAST:event_btnDlgEliminarActionPerformed

    private void btnDlgCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDlgCancelar1ActionPerformed
        this.setEnabled(true);
        dlgEliminar.dispose();
        verBotones(true);
        limpiarCampos();
        this.setVisible(true);
    }//GEN-LAST:event_btnDlgCancelar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarModificar;
    private javax.swing.JButton btnCancelarModificar;
    private javax.swing.JButton btnDlgAceptar;
    private javax.swing.JButton btnDlgCancelar;
    private javax.swing.JButton btnDlgCancelar1;
    private javax.swing.JButton btnDlgEliminar;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnInsertarUsuario;
    private javax.swing.JButton btnModificarUsuario;
    private javax.swing.JComboBox<String> cmbSexoUsuario;
    private javax.swing.JDialog dlgEliminar;
    private javax.swing.JDialog dlgModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rdAdministradorUsuario;
    private javax.swing.JTextField txtApellidoUsuario;
    private javax.swing.JTextField txtCodigoUsuario;
    private javax.swing.JTextField txtDlgCedula;
    private javax.swing.JTextField txtDlgCedulaEliminar;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JPasswordField txtPassUsuario;
    private javax.swing.JPasswordField txtRepPassUsuario;
    private javax.swing.JTextField txtTelefonoUsuario;
    // End of variables declaration//GEN-END:variables
}
